//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlTemplateXAF.Web.Controls {
    
    
    public partial class DashboardWebUserControl {
        
        /// <summary>
        /// DeliverablesUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HtmlTemplateXAF.Web.Controls.DeliverablesKPIWebUserControl DeliverablesUC;
        
        /// <summary>
        /// ProjectsUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HtmlTemplateXAF.Web.Controls.DeliverablesKPIWebUserControl ProjectsUC;
    }
}
